server:
  port: 9002

spring:
  application:
    name: mes-system
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  data:
    redis:
      port: 6379

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.mes.system.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Token 配置
token:
  header: Authorization
  secret: mescloudmescloudmescloudmescloudmescloud
  expireTime: 120
  prefix: "Bearer "

# 日志
logging:
  level:
    com.mes: debug
